### PR TITLE
Fixed Gc in surfing boundary problem #180

### PR DESCRIPTION
**Pull request by irvin-rodriguez**
Closes issue #180

### CODE REVIEW

**Comment by irvin-rodriguez** [comment]
@lyyc199586 Could you double check this?

**Comment by lyyc199586** [comment]
> @lyyc199586 Could you double check this?

looks correct to me

**Comment by lyyc199586** [comment]
> @lyyc199586 Could you double check this?

wait, you are modifying other files in this PR (look at files changed), you should create a clean branch from orgin/devel, then modify only the surfing tutorial.

**Comment by TheGreatCid** [comment]
Ah shoot, Ill help him fix that

**Pull request closed without merging**
