### PR TITLE
Clean up linear hardening

### LINKED ISSUE #100: Add a linear hardening law

### PR DESCRIPTION
**Pull request by hugary1995**
Add a documentation page for linear hardening.
Add a regression test for linear hardening.

close #100

### CODE REVIEW

**Comment by hugary1995** [comment]
@Sina-av See this PR. All models in RACCOON should be documented and tested. Here I am adding documentation and tests for your linear hardening model. Feel free to follow what I am doing here in your future contributions.

I am also renaming the class from `LinearIsotropicHardening` to `LinearHardening` for consistency. We're not really supporting any anisotropic yield surface for now.

**Comment by Sina-av** [comment]
@hugary1995 Thanks a lot for the comments. For sure I'll follow the same procedure for future files.
Just as another point, in the documentation for LinearHardening, degradation function is acting on plastic energy, which would make g(d) to enter the derivative of plastic energy w.r.t plastic strain ep. However, this is not the case in the code at the moment (as I mentioned yield surface is not degraded). So there might be a little inconsistency there. (To solve this we can simply add g(d) to the code or remove g(d) from acting on plastic energy directly.)
Thanks.

**Comment by hugary1995** [comment]
> Just as another point, in the documentation for LinearHardening, degradation function is acting on plastic energy, which would make g(d) to enter the derivative of plastic energy w.r.t plastic strain ep. However, this is not the case in the code at the moment (as I mentioned yield surface is not degraded). So there might be a little inconsistency there. (To solve this we can simply add g(d) to the code or remove g(d) from acting on plastic energy directly.)

Good catch! I'll correct that.

**Comment by hugary1995** [comment]
Fixed.

**Comment by Sina-av** [comment]
Hi @hugary1995!
I was going over the code again, and noticed another inconstancy.
In the following line, plastic degradation is acting just on the initial yield stress:
https://github.com/hugary1995/raccoon/blob/d680456e6f69628e76c547a35da419165c46bf79/src/materials/hardening_models/LinearHardening.C#L63
Where it should act on the whole isotropic hardening term, i.e.:
```
 return _gp[_qp] * ( _sigma_y[_qp] + _H[_qp] * ep); 
```
Thanks.

**Comment by hugary1995** [comment]
@Sina-av I've no idea why GitHub didn't give me a notification from your message. Probably because this issue had been closed? I've no idea. I saw your message just now when I was cleaning my email inbox.

I'll fix this up now!

**Pull request merged**
