### PR TITLE
complete doc/content/tutorial 03 & 04

### PR DESCRIPTION
**Pull request by lyyc199586**
How about now?

### CODE REVIEW

**Comment by hugary1995** [comment]
Several things:

- You accidentally committed a change to the submodule moose -- I've fixed that for you.
- It seems that you were just copying the content of tutorial 2 to tutorials 3&4. That's not ideal. In every tutorial, we want to demonstrate something that's not been mentioned in previous tutorials. I took a stab at making some improvements. Please checkout the changes and see if you are okay with them.

Since I force pushed to your branch to fix the submodule, you need to do a hard reset to see the updates:
```
git fetch --all
git reset --hard YourRemoteName/doc_yc2
```
after which you can rebuild raccoon and rebuild the documentation:
```
git submodule update --recursive
make -j N
cd docs
./moose_docs.py build --serve
```

**Comment by hugary1995** [comment]
Once you are okay with the changes I made, I'll merge this PR. Thanks!

**Comment by hugary1995** [comment]
@TheGreatCid , Yuanchen and I are adding the fiber-reinforced matrix tutorial (tutorial 4) here. Since you are more familiar with this problem than we are, feel free to take a look and tell us if anything is missing. In the future, It would be great if you could add several pictures showing your results (optionally compared with Bourdin's results) and add a video in the gallery on the homepage.

**Comment by hugary1995** [comment]
@lyyc199586 I added you as a collaborator. Once you accept the invite, your future PRs will automatically trigger the status checks.

**Comment by lyyc199586** [comment]
Great, thank you!

**Comment by lyyc199586** [comment]
> Several things:
> 
> * You accidentally committed a change to the submodule moose -- I've fixed that for you.
> * It seems that you were just copying the content of tutorial 2 to tutorials 3&4. That's not ideal. In every tutorial, we want to demonstrate something that's not been mentioned in previous tutorials. I took a stab at making some improvements. Please checkout the changes and see if you are okay with them.
> 
> Since I force pushed to your branch to fix the submodule, you need to do a hard reset to see the updates:
> 
> ```
> git fetch --all
> git reset --hard YourRemoteName/doc_yc2
> ```
> 
> after which you can rebuild raccoon and rebuild the documentation:
> 
> ```
> git submodule update --recursive
> make -j N
> cd docs
> ./moose_docs.py build --serve
> ```

Thanks, now I kinda understand the workflow of working togather with git and the philosophy of writing docs for raccoon.

Please merge.

**Comment by TheGreatCid** [comment]
> @TheGreatCid , Yuanchen and I are adding the fiber-reinforced matrix tutorial (tutorial 4) here. Since you are more familiar with this problem than we are, feel free to take a look and tell us if anything is missing. In the future, It would be great if you could add several pictures showing your results (optionally compared with Bourdin's results) and add a video in the gallery on the homepage.

Seems like its been merged already, but I will take a look at it later and let you know if there is anything missing or if I intend to add anything

**Comment by hugary1995** [comment]
Crap, I didn't notice that you pushed yet another commit after I approved this PR, and you committed submodule moose again! I need to revert this and fix it.

**Comment by lyyc199586** [comment]
what? but I only did `git submodule update --init --recursive`

**Comment by lyyc199586** [comment]
let's meet when you have time

**Comment by TheGreatCid** [comment]
> what? but I only did `git submodule update --init --recursive`

What command are you using to add files to commit?
If you are doing `git add . ` then it will add moose to your committed files/directories

**Comment by lyyc199586** [comment]
> > what? but I only did `git submodule update --init --recursive`
> 
> What command are you using to add files to commit? If you are doing `git add . ` then it will add moose to your committed files/directories

NO, I think I add them seperately.

So, should I do `git submodule update --init --recursive` each time when I want to PR?

**Comment by hugary1995** [comment]
So normally if you do `git add -A .`, it will add your local changes, ignoring any submodule change. To add a submodule update, you have to specifically request for it using `git add moose`.

If your submodule is out-of-sync, you should use `git submodule update` (or `git submodule update --recursive` to do it recursively for submodules of the submodules), unless you _really_ intend to commit a submodule change. You can tell whether your submodule is in-sync or not using `git status`.

**Pull request merged**
